data:
  cifar10_dir: ../dataset/cifar-10-python/cifar-10-batches-py
model:
  channels:
  - 64
  - 128
  - 256
  dropout_rate: 0.2
  gradient_clip: 0.1
  name: EfficientResNet
  num_blocks:
  - 4
  - 4
  - 3
  squeeze_and_excitation: true
  use_bottleneck: false
  use_dropout: true
training:
  autoaugment: false
  batch_size: 128
  cutout: true
  data_augmentation: true
  epochs: 500
  learning_rate: 0.1
  lr_scheduler: CosineAnnealingLR
  mixup: true
  mixup_alpha: 1.0
  momentum: 0.9
  normalization: true
  num_workers: 8
  optimizer: SGD
  weight_decay: 0.0005
